### ISSUE TITLE
Question: Why include modernizr & jquery in bower setup

### ISSUE THREAD

**Issue by utx0** [horacioh/foundation-smacss-middleman#1]
Why include modernizr & jquery in the bower setup when you include them via a cdn? Am I missing something here? 

Thanks Luke

P.S Just started working with this template for a project I'm working on. :)

**Comment by horacioh** [comment]
Hi!

its good to hear that something I made is usefull for someone :) thx man!

I leave the cdn links so you can choose, either included via bower (locally in your project) or via cdn (not hosted on your site) Its your choice :)

hope this help!

P.S.: I'm Horacio, no Luke! :)

**Comment by utx0** [comment]
Ok cool thanks.
