### ISSUE TITLE
Question: How is this template smacss enabled? 

### ISSUE THREAD

**Issue by utx0** [horacioh/foundation-smacss-middleman#2]
Hi there,

Still getting my head about using SMACSS (One of the reason why I am playing with this template), but I cant seam to understand how this template is SMACSS enabled? 

Can you advise me how you use this template with a SMACSS approach?  

I would have expected files in the stylesheet directory for base, layout, states and then just create files for each module? 

Love to know your workflow. 
Much appreciated.
Luke

**Comment by horacioh** [comment]
thanks for the observation lukekhamilton, that's something I delete with the new commit. will enable it ASAP
